apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/image.toolkit.fluxcd.io_imagerepositories.yaml
- bases/image.toolkit.fluxcd.io_imagepolicies.yaml
# +kubebuilder:scaffold:crdkustomizeresource
